### ISSUE TITLE
changelog old?

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/roswiki#147]
E.g. 

for people package,
- [repositories.ros.org shows 1.0.10 is synched](http://repositories.ros.org/status_page/ros_jade_default.html?q=people)
- [changelogs is 1.0.9](http://docs.ros.org/jade/changelogs/people/changelog.html).
 (It's latest version was [listed to rosdistro 18 days ago](https://github.com/ros/rosdistro/pull/10192)).

rtmros_hironx
- [repositories.ros.org shows 1.1.3 is synched](http://repositories.ros.org/status_page/ros_indigo_default.html?q=rtmros_hironx)
- [changelog is 1.0.37 (2015-09-11)](http://docs.ros.org/indigo/changelogs/rtmros_hironx/changelog.html)

**Comment by dirk-thomas** [comment]
First of all the released Debian packages and the changelog are independently generated. But I checked that the doc job for Jade `people` ran correctly. The changelog file has simply not been updated in the upstream repo: https://github.com/wg-perception/people/blob/indigo-devel/people/CHANGELOG.rst

For `rtmros_hironx` that is a different story. Upstream contains a newer version: https://github.com/start-jsk/rtmros_hironx/blob/indigo-devel/rtmros_hironx/CHANGELOG.rst
And the doc job ran and uploaded its file (http://build.ros.org/view/Idoc/job/Idoc__rtmros_hironx__ubuntu_trusty_amd64/) but the content of the `changelog.html` file. Looking into the cloned content of the repository it seems that it also only contains old information: http://build.ros.org/view/Idoc/job/Idoc__rtmros_hironx__ubuntu_trusty_amd64/ws/catkin_workspace/src/rtmros_hironx/rtmros_hironx/CHANGELOG.rst/*view*/ After checking the rosdistro entry for the repo the reason becomes obvious - the repo uses the hydro branch for the indigo distro: https://github.com/ros/rosdistro/blob/3a12494ed2bcc7d253271831f3512506117415ff/indigo/distribution.yaml#L9558

Since all of the problems are due to upstream issues I will close this. Please consider updating the changelog file of people and the rosdistro entry of `rtmros_hironx`.

**Comment by 130s** [comment]
Thanks Dirk, I was a little too careless for this.
