### ISSUE TITLE
manifest.xml file is still referenced in package documentation wiki pages

### ISSUE THREAD

**Issue by becomesaflame** [ros-infrastructure/roswiki#164]
Many pages dealing with documentation still call out manifest.xml instead of package.xml.  These include at least:

[rosdoc](http://wiki.ros.org/rosdoc)
[PackageDocumentation](http://wiki.ros.org/PackageDocumentation)
[Epydoc](http://wiki.ros.org/Epydoc)
[Doxygen](http://wiki.ros.org/Doxygen)

**Comment by becomesaflame** [comment]
There also appear to be separate but identical pages for [catkin/package.xml](http://wiki.ros.org/catkin/package.xml) and [Manifest](http://wiki.ros.org/Manifest).  Should one of these redirect to the other?

**Comment by wjwwood** [comment]
For any pages that mention `manifest.xml` instead of `package.xml`, feel free to update them if you think you can. Keeping the wiki update is a shared task. I had a look at the ones you linked:

> rosdoc

This one is deprecated, as it says at the top:

> DEPRECATION NOTICE: rosdoc is now deprecated in favor of rosdoc_lite

> PackageDocumentation

This one is mentions the `package.xml` as well, with a TODO to document or link to it. Since you already found the `package.xml` pages, maybe you could add a link to the appropriate section?

> Epydoc
> Doxygen

These are both in need of updates. I'm not sure what to put in there off-hand. It's probably been superseded by `rosdoc_lite`. You might want to open an issue on their issue tracker: https://github.com/ros-infrastructure/rosdoc_lite/issues

As for the duplicate pages for `package.xml`, I think that's a historical issue where the `catkin/package.xml` page was created when building up `catkin` docs and the `Manifest` page was later updated when `catkin` because the default option. It would be nice to de-duplicate the pages and include one in the other or something like that.

**Comment by dirk-thomas** [comment]
The two catkin / Manifest pages are already reusing the same content. One of them is including the other one.

**Comment by wjwwood** [comment]
Yup, I only checked one I think. So there's nothing that needs to be done there.

**Comment by becomesaflame** [comment]
I updated references where they could clearly be replaced, and opened ros-infrastructure/rosdoc_lite#64 to request feedback on the examples that reference rosdoc config files or manifest.xml syntax.

**Comment by wjwwood** [comment]
@becomesaflame thanks!
