### ISSUE TITLE
Meta package "robot"

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/roswiki#177]
Found so far at the following, only with Kinetic selected. What is this `robot` category? Meta package?

http://wiki.ros.org/robot_state_publisher?distro=kinetic
http://wiki.ros.org/xacro?distro=kinetic

![xacro_wiki_kinetic](https://cloud.githubusercontent.com/assets/1840401/17033421/ec789776-4f32-11e6-939f-bdc5020c765c.png)

**Comment by dirk-thomas** [comment]
The `robot` metapackage is specified in [REP 142](http://www.ros.org/reps/rep-0142.html).

**Comment by 130s** [comment]
Thanks for the informative link.

My question now narrows down: for some packages in for instance `robot` metapkg, their wiki page doesn't say that they are in `robot` metapkg. E.g. http://wiki.ros.org/control_msgs?distro=kinetic

![screenshot from 2016-07-21 11-50-40](https://cloud.githubusercontent.com/assets/1840401/17034875/682fcd0c-4f39-11e6-87c6-ec6dea5f7b0e.png)

Not a big deal after all, but it'd be nice for end users if the behavior is consistent. Personally I'd prefer the metapkg grouping is not shown on wiki, considering it's not for end users (which is how I understand the purpose from [rep-0108](http://www.ros.org/reps/rep-0108.html)).

**Comment by dirk-thomas** [comment]
The metapackage group is shown since it can be useful in case like http://wiki.ros.org/roscpp to see its "siblings". And since the metapackages specified in the REP are technically the same they can't be treated differently.

To the question why `control_msgs` doesn't show the metapackage it is obviously in: The information shown in the wiki is coming from the `manifest.yaml` files which are generated by the doc jobs. While [roscpp](http://docs.ros.org/kinetic/api/roscpp/manifest.yaml) contains its meta package [control_msgs](http://docs.ros.org/kinetic/api/control_msgs/manifest.yaml). Looking at the involved doc jobs that is like because [control_msgs # 1(]http://build.ros.org/job/Kdoc__control_msgs__ubuntu_xenial_amd64/) run before the [metapackages # 1](http://build.ros.org/job/Kdoc__metapackages__ubuntu_xenial_amd64/) were being documented.

I triggered the `control_msgs` doc job (which will take a time since the farm is currently busy) which will update the `manifest.yaml` which will make the wiki show the metapackage consistently.

For cross referencing to work each doc job must at least run twice (first all doc jobs run the first time, then they need to run a second time to pick up the meta information from all the other doc jobs). This hasn't happened for this package since it was released into Kinetic (and since it didn't change the farm doesn't retrigger the job automatically).

**Comment by 130s** [comment]
Then I support the current spec then as long as the behavior looks consistent to the end users. Thanks for handling all these.
