### ISSUE TITLE
ROS and its security

### ISSUE THREAD

**Issue by dabeegmon** [ros-infrastructure/roswiki#181]
(Starting with a preamble) A total noob at programming but thinking I am going to be learning by what I would like to do. Have been running Debian for quite a few years as I wanted some constancy and have been slowly increasing my security understanding as our world is piling onto the internet wagon.
Have run an ubuntu system for my wife for a number of years. I have gotten really anal about security after I found that I am findable in the first page of a ms google search on my first name. 

Learnt to describe the difference between windows and linux by comparing their security. Security on windows is very much like a screen door - - - it can be made useful but its impossible to close ALL the holes, on the other hand linux (and to a generally high level debian) is a little bit like a property with a 4 m (12 foot) tall brick wall around it and the door is made of solid 5 cm (2 in) steel. There is a man door in the big door but one needs to know how to open it and its not easy to open and it takes a conscious choice to open it.

Even saying this there have been more than a few times that I have been frustrated and had to spend huge amounts of time repairing my mistakes when I improperly gave commands whilst I was logged in as root but then I new that I was doing things that could compromise my system. Some of these 'moments' have been the teachings that have encouraged me to do more to secure my system. As I have gone to adding a server setup to my business I have had to learn about networking and its security, have started working with virtual systems as well and have worked through some things so that I could place my copy of windows in an electronic equivalent to a hardend very high security facility. Underlying all these ventures has been a recognition that security is one of my primary needs AND responsibilities to myself, my family and my business and by extension even to the rest of the world.

So I have been somewhat surprised to find that even for the debian installations that there was the expectation that I would use sudo rather than root. Posted a question about that and was then directed to ROSs (IIRC that was how it was written) or secure ROS. That is a very good thing IMO. Security starts from the basics of the system and cannot be an 'add-on'. So I read through secure ros and found that the area was under heavy development but that there really wasn't anything available to read. (Now for my questions.)

What I was able to read the security is for operating with to make sure that the automaton does not bring malware of some form back to the home system. Has a major security window been overlooked? I believe that it has. Using root to implement changes to a system can help increase the security of hardware. Using a single level of log on (sudo and its user vs using user AND root (2 log ons)) inherently reduces the security of a system. If I had the knowledge (and skills) to delineate how to do this I would be doing just that, but I don't have those skills. So rather I ask - - - can we increase the security of an ros hardware system by going to a dual (and if there is justification for more, fine) level of logons for the manipulation and use of the hardware?

(I am interested in assisting with the documentation for such a new installation system but just don't think I would be useful for much more than that and being a beta tester for it.)

Thanks for listening and considering.

**Comment by tfoote** [comment]
Hi @dabeegmon, please ask questions on http://answers.ros.org This is an issue tracker where we track bugs in the website implementation. 

There are definitely a lot of different practices around security and depending on your application there are different approaches with different strengths.

**Comment by dabeegmon** [comment]
Very interesting as that is where I first raised the issue and was told that that was NOT the place and that I was to go here. You have killed this here - - - so where do I go - - - I suppose that what I'm being told is that this isn't of interest and that I'm supposed to get lost - - - is that true?

**Comment by wjwwood** [comment]
@dabeegmon I don't think the takeaway is "get lost". Can you post a link to your previous question? Just because this isn't the right place to discuss the topic doesn't mean it isn't a topic worth discussing.

Even better than answers.ros.org, this might be better raised on our mailing lists so that it reaches a wider audience: http://discourse.ros.org/c/general You might be asked to further scope your discussion in a sub category of that website.

ROS is a big community, please don't get discourage if you get bounced around at first until you find the right part of the community to talk with.

**Comment by gavanderhoorn** [comment]
I was the one that advised @dabeegmon to post here on the roswiki tracker ([how to convert debian root to sudo with security](http://answers.ros.org/question/242625), as I felt that some discussion about practices might make sense before going in and changing the installation tutorials.

As I remembered some earlier discussion issues here, I figured this particular issue might also be something to start here.

Perhaps `discourse.ros.org` would be a better place. I should've thought of that @dabeegmon, and referred you there.

**Comment by gavanderhoorn** [comment]
@dabeegmon wrote:
> [..] was told that that was NOT the place [..]

well, I didn't exactly say that it was 'not the place', I suggested that a discussion on a different site than ROS Answers might be more suitable, and increase your chances of getting relevant input.

**Comment by wjwwood** [comment]
I see, well since the topic was about documentation, I can see how you might point @dabeegmon here. In my mind, this repository's issue tracker is for technical issues and content and layout issues with things on the wiki, so long as they don't match some other issue tracker, i.e. issues with a package's wiki pages could be better posted on their issue trackers. But I can see why this topic could be discussed here.

Sorry @dabeegmon, it wasn't our intention to give you the run around, but as you can see even we don't have complete consensus on what should go where. I still think that posting this topic to discourse.ros.org will get you the most people looking at it. This issue tracker is not watched by very many people.

Also, I'd suggest that you try and shorten your initial post if possible, or add a [tldr](https://en.wikipedia.org/wiki/Wikipedia:Too_long;_didn%27t_read) paragraph. That way more people get to the meat of the issue more quickly. Also, don't be discouraged if people don't respond right off. Many people will read it and then take a few days to digest it before they have time to formulate a response. If and when there is a concrete proposal on how to change the documentation and there are logistical concerns, then this issue tracker may become the appropriate place to post again. Thanks!

**Comment by tfoote** [comment]
And when you do post, please link to previous parts of the discussion. Aka [here](https://github.com/ros-infrastructure/roswiki/issues/181) and the [answers.ros.org question](http://answers.ros.org/question/242625) so that others can read more history if they want.

**Comment by dabeegmon** [comment]
What I am finding incredibly challenging is understanding the differences in what is wanted and where. One place says detail the next says minimal. Interesting is that a login (and thereby account) is asked for on many of the different parts. Its almost like there are x number of discreet parts to ros and each one has a different way of doing things. There doesn't feel like there is a lot of cohesiveness and that's challenging in a huge project like ros.

I've become quite anal about security after I found out how findable I was on the web. I don't do hesitant having this problem with being passionate and involved in what I'm into and I would rather not have all the world connect to me for kicks and giggles. IMO we don't really have much privacy left and security isn't that much better. The two are different issues but security is part of privacy and vice versa. Sorry - - - this is only one of my hobby horses!

So how would I link the previous parts of this discussion?
Would it be necessary to include all parts of any discussion? (ie could parts be not linked)

**Comment by gavanderhoorn** [comment]
> So how would I link the previous parts of this discussion?
Would it be necessary to include all parts of any discussion? (ie could parts be not linked)

There are only 'two parts' to this, right? @tfoote just means to include a link to your ROS Answers question and to this issue. Basically the links he already included in his https://github.com/ros-infrastructure/roswiki/issues/181#issuecomment-243585241.
