### ISSUE TITLE
package header source entry - where is this retrieved from?

### ISSUE THREAD

**Issue by mgruhler** [ros-infrastructure/roswiki#286]
A question about the autogenerated header information of the packages.

I've taken over the maintainership of the [soem ROS package](http://wiki.ros.org/soem).

I just noticed the the `source` entry in the package information still links to the old repo for `kinetic`, wheras it links to the correct/new one for `melodic`. (is there a way to link directly to the different distro versions?)

I've previously released with the new repo into `melodic` (first release to `melodic` without changes to the `kinetic` version, so I didn't release there), but just yesterday I triggered new releases to both distros. As the new change has been merged for `kinetic` (ros/rosdistro#22300) and `melodic` (ros/rosdistro#22301) and is thus now available in `rosdistro`, I'm wondering where the different information comes from...

The `Bug/Feature Tracker` section links correctly, only the `source` does not. Will this be updated once the new released package has been sync'd? Or do I need to change something else? I [changed the `repository` header](http://wiki.ros.org/soem?action=diff&rev1=7&rev2=8) on the ROS wiki, but I honestly don't know what this does.

Any hints are appreciated :-)

**Comment by tfoote** [comment]
That "repository" header is just a comment. 

Some of the wiki documentation header comes from the individual doc jobs. The last time it was run was Sep 3rd for Kinetic: http://docs.ros.org/kinetic/api/soem/

![Screenshot from 2019-09-19 23-53-10](https://user-images.githubusercontent.com/447804/65305685-aab2b200-db38-11e9-8b30-6c91cb1bd823.png)

Updated by the last doc job: http://build.ros.org/view/Kdoc/job/Kdoc__soem__ubuntu_xenial_amd64/5/

Since there's been no changes to the source tree the doc job is optimized not to rerun w/o a change. 
```
Started on Sep 18, 2019 3:45:00 AM
Using strategy: Default
[poll] Last Built Revision: Revision 5c038d75119d5f9dc71d48211d22c038f85c3142 (origin/master)
No credentials specified
 > git --version # timeout=10
 > git ls-remote -h https://github.com/smits/soem.git # timeout=10
Found 3 remote heads on https://github.com/smits/soem.git
[poll] Latest remote head revision on refs/heads/master is: 5c038d75119d5f9dc71d48211d22c038f85c3142 - already built by 5
Done. Took 0.54 sec
No changes
```

Each doc job only polls every 3 days to keep the buildfarm from getting overloaded. So if you've made changes since that polling period it will be picked up in a day or two.

Some of the other content comes from the devel job data and gets overlayed as well which is likely why you're seeing a partial update. https://github.com/ros-infrastructure/roswiki/blob/8f7277dcd4a105e3b4c4e3d77a129dcc76064528/macro/headers.py#L577

Ad the devel job has run more recently: http://build.ros.org/view/Kdev/job/Kdev__soem__ubuntu_xenial_amd64/

When the doc job runs in the next day or so it should update the wiki header.

**Comment by mgruhler** [comment]
Cool, thx for the explanation @tfoote.
This helps a lot. So I'll just check the wiki in a few days, should be updated then.

**Comment by tfoote** [comment]
Yeah, I'd expect it on the 21st having last polled on the 18th.
