### ISSUE TITLE
PackageHeader macro not working for ROS2 packages

### ISSUE THREAD

**Issue by max-krichenbauer** [ros-infrastructure/roswiki#291]
If a package is being built on http://build.ros2.org, then the documentation does not end up on http://docs.ros.org/ and the generation of the package header in the wiki fails.

Example: http://wiki.ros.org/webots_ros2?distro=dashing

Apparently, the documentation is also not available on http://docs.ros2.org/ 

If someone could let me know if/how the Wiki should be able to handle pages for ROS2 packages, I can work on providing a PR.

**Comment by dirk-thomas** [comment]
The package header macro uses information generated by the repository specific `doc` jobs run on the ROS 1 buildfarm and the generic documentation job collecting all metadata from packages which don't have a dedicated `doc` job.

For ROS 2 there is at the moment no equivalent to these `doc` jobs and therefore the metadata is not available. Also it is not planned to add ROS 2 specific documentation content to wiki.ros.org since the current technology used for the Wiki (MoinMoin) is already well beyond its supported scale.

**Comment by max-krichenbauer** [comment]
Understood. Thank you for the explanation!
