### ISSUE TITLE
Add Google Translate toolbar to the ROS wiki

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [ros-infrastructure/roswiki#307]
Google Translate is really quite good these days. Can you integrate it into the wiki so people can easily choose their language of choice for automatic translation? 

This has 2 huge benefits:

1. It allows translation to tons of languages to help users.
1. It perfectly syncs the wiki updates in English to all translations, as they are translated live.

A quick [google search for "add google translate page button to website"](https://www.google.com/search?q=add+google+translate+page+button+to+website&oq=add+google+translate+page+button+to+website&aqs=chrome..69i57.8992j0j7&sourceid=chrome&ie=UTF-8) yields quite a few results. 

Ex: https://www.geeksforgeeks.org/add-google-translate-button-webpage/

Here are some sample translations of the ROS wiki as shown on the top of this page: http://wiki.ros.org/Documentation.

> **Automatic Language Translations:** Google Translate can automatically translate any page on the internet to dozens of languages. Ex: here is this ROS wiki page in [Spanish](https://translate.google.com/translate?hl=&sl=en&tl=es&u=wiki.ros.org), in [French](https://translate.google.com/translate?hl=&sl=en&tl=fr&u=http%3A%2F%2Fwiki.ros.org%2F), and in [Simplified Chinese](https://translate.google.com/translate?hl=&sl=en&tl=zh-CN&u=http%3A%2F%2Fwiki.ros.org%2F). Simply click on one of these then choose your target language from the drop-down menu at the top of the page.

**Comment by tfoote** [comment]
Google Translate is getting much better but there's also arguably many other online translators that are also good as well. For translating the whole website there are many browser plugins that can provide this and it's built into chromimum based browsers.

We also have several community efforts to actually translate the wiki manually which in many cases of technical documentation are still better than automatic translation. 

Overall I'd rather not add another element that everyone is required to load that will pull resources from another website incurring bandwidth and latency. And with the availability of browser level translation a top level button seems to force one choice rather than provide functionality that is unavailable otherwise. And unless we're going to validate the documentation generated by google translate I'd rather not endorse it over some other translation service. As adding a button to it would suggest that it's supported by us.

**Comment by tfoote** [comment]
Related I reverted the change to add links to Google Translate from our header. That's a distraction from the main message and an external automated translation service should not be the 3rd most important thing we're communicating. https://wiki.ros.org/action/diff/Documentation?action=diff&rev1=188&rev2=189 That paragraph is longer than our summary overview and takes up a large fraction of the content above the fold.

**Comment by ElectricRCAircraftGuy** [comment]
I see your point. Sounds fine. There were a ton of edits your revert just undid. Here's the page roughly as it was a few minutes ago. 

```
''ROS (Robot Operating System) provides libraries and tools to help software developers create robot applications. It provides hardware abstraction, device drivers, libraries, visualizers, message-passing, package management, and more.  ROS is licensed under an open source, BSD license.''

'''Available Translations:''' [[de|German]] | [[es|Spanish]] | [[fr|French]] | [[it|Italian]] | [[ja|Japanese]] | [[ko|Korean]] | [[pt_BR|Brazilian Portuguese]] | [[pt|Portuguese]] | [[ru|Русский (Russian)]] | [[th|Thai]] | [[tr|Turkish]] | [[cn|简体中文]] | [[ua|Ukrainian]]  |  [[vn|Vietnamese]]

## Table of contents up to 4 heading levels deep
<<TOC(4)>>

== ROS Main: ==
  1. '''[[ROS/Introduction|Introduction]]'''
    . Answers the question, "What is ROS?"
    . See also: '''[[ROS/Concepts|Concepts]]'''
  1. '''[[ROS/Installation|Installation]]'''
    . Install ROS on your machine.
    . See also: '''[[ROS/EnvironmentVariables|Environment Variables]]'''
  1. '''[[ROS/StartGuide|Start Guide]]'''
    . Learn about various concepts, client libraries, and technical overview of ROS.
  1. '''[[ROS/Tutorials|Tutorials]]'''
    . Step-by-step instructions for learning ROS hands-on
  1. '''[[Get Involved]]'''/Contribute
    . How to get involved with the ROS community, such as submitting your own repository or editing the ROS Wiki.
  1. '''[[Support]]''' 
    . (See also the [[#Wikis.2C_Bug_Reports.2C_.26_Help:|bug report section at the bottom of this page]])
    . What to do if something doesn't work as expected.
  1. '''[[Quality|ROS Software Quality Hub (Quality Assurance)]]'''
    . How to ensure that your ROS-based systems and your contributions to ROS are of high quality.
  1. '''[[Tools|Common Tools]]'''
    . Common tools for developing and debugging ROS software.
    . See also: '''[[ROS/CommandLineTools|ROS Command-line Tools]]'''

== Distributions, Packages, & Libraries: ==
  1. '''[[Distributions]]'''
    . View the different release Distributions for ROS.
  1. '''[[https://index.ros.org/packages/page/1/time/|Packages]]'''
    . Search the 2000+ software libraries available for ROS.
  1. '''[[APIs|Core Libraries]]'''
    . APIs by language and topic.

== Robots & Hardware: ==
  1. '''[[Robots]]'''
    . Robots that you can use with ROS.
  1. '''[[Sensors]]'''
    . Sensor drivers for ROS.
  1. '''[[Motor Controller Drivers|Motors]]'''
    . Motor controller drivers for ROS.

== Publications, Courses, and Events: ==
  1. '''[[Papers]]'''
    . Published papers with open source implementations available.
  1. '''[[Books]]'''
    . Published books with documentation and tutorials with open source code available.
  1. '''[[Courses]]'''
    . Courses using or teaching ROS.
  1. '''[[Events]]'''
    . Past events and materials based on ROS.

== Wikis, Bug Reports, & Help: ==
  1. The '''[[Support]]''' page previously linked-to in the "ROS Main" section above.
  1. Main wiki (this wiki): '''http://wiki.ros.org'''
  1. How to edit the ROS Wiki: '''[[EditingTheWiki]]'''
  1. '''[[https://en.wikipedia.org/wiki/Robot_Operating_System|Wikipedia: Robot Operating System]]'''
  1. Bugs & Feature Requests:
    1. ROS Main: <<GitHubIssues(ros/ros)>>
      1. '''https://github.com/ros/ros/issues''' --> "New Issue"
    1. ROS Wiki (this Wiki): '''https://github.com/ros-infrastructure/roswiki/issues''' --> "New Issue"

~-There are several [[Mirrors|mirrors]] of this wiki for use around the world-~
```

**Comment by ElectricRCAircraftGuy** [comment]
As this is the main Documentation landing page, I see a ton of improvements to make to it, which is what I was working on, as it's missing a bunch of links that are obscure, scattered, and otherwise hard to find. Your revert removed all of those too. One of those is the EditingTheWiki link, as that's a nearly impossible-to-find page right now: http://wiki.ros.org/EditingTheWiki.

**Comment by tfoote** [comment]
Adding a like to the Editing the wiki would be much better to add to the Wiki heading on the Contributing page: https://wiki.ros.org/Contributing  The vast majority of users are not looking to edit the wiki.

The support page is already linked.
A link to yourself is not useful. 
This is the resource that wikipedia links to /cites. Linking back to a 3rdparty summary is a little bit backwards. 
The Issues link to ros/ros on github is unlikely to be the correct place for most issues. It's not a catchall and shouldn't be linked here.

I also saw that you added EditTheWiki at the top of the Get Involved page. https://wiki.ros.org/action/diff/Get%20Involved?action=diff&rev1=92&rev2=93 It definitely should not be there. That's not the first thing that someone who wants to get involved should do, they should start with reading most of the content listed there and once they have context, then think about editing. It's valuable to have there, but shouldn't be higher on that page than reading the latest news sources and finding out what the context is. There are many times when a new user who has made a mistake earlier in the tutorial has edited later steps to "fix" their problem, for example just adding sudo to any or every command because they got their permissions wrong by running sudo once incorrectly during an initial stage. And similiarly if you just start extending a specific page unless you've read most of the related pages you can quickly lead to duplicate content. Such as maybe a link would be better rather than writing the content again.
